### ISSUE TITLE
Steem/mvest should increase monotonically

### ISSUE THREAD

**Issue by MWaser** [aaroncox/steemdata-reward-history#1]
steemdata-reward-history/historical/mvest_history.csv and steemdata-reward-history/historical/mvest_history.js show steem/mvest as fluctuating.  This is NOT correct. 

I would *love* to get the correct values . . . .

**Comment by aaroncox** [comment]
The values themselves were derived on a best-effort basis by using historical vesting withdraws, which is why they fluctuate instead of steadily increase as you'd expect. 

I'd love to get 100% absolute values for this as well, but I don't know of a source of truth for those values that exists anywhere.

**Comment by MWaser** [comment]
So . . . the source of truth is to just actually run the formula embedded in the blockchain.  I *think* that it has been constant since Steem went public in July 2016 (but there were multiple versions before that).

Of course, doing that is a royal flaming pain and, re-reading my original comment, I apologize as it seems harsh in retrospect.

**Comment by aaroncox** [comment]
No worries! Sorry it took me so long to respond, I've been disconnected for a couple weeks from my work now dealing with a nasty flu/cold. 

From my understanding of how it all works, it's not just a simple formula that you can actually run. The steem_per_mvest number is derived based on how much steem is in the `total_vesting_fund_steem` and how many vests are shown in `total_vesting_shares`. I also believe that those values change as people power up and power down. This all makes getting any sort of absolute value for a particular point in time incredibly difficult. 

The only way I could think to get those values at this point (since no one to my knowledge has any historical records) would be to create a modified version of the steem blockchain, in which as the blockchain was replayed, each block it would save a snapshot of that data out to an external data source. I personally am not sure how to accomplish that, though I'd have a ton of uses for a version that could do so, this included.

**Comment by MWaser** [comment]
:-)  You are absolutely correct.  I was intending and know in the abstract how to accomplish paragraph three -- but it would likely take me (someone who has played with the code -- but over 15 months ago) a solid week or two of effort -- which doesn't seem worthwhile for the payoff.

**Comment by MWaser** [comment]
BTW, in case you're curious . . . . I needed the info to thoroughly do my taxes and decided to use a smoothing algorithm on the numbers so that they were steadily increasing -- albeit at a slightly jerky rate.  I'd love it if you continued updating the numbers as I'll need them again next year.  Thanks!  ;-)

**Comment by aaroncox** [comment]
Makes total sense and I needed them for the same reason 👍 

The script used to generate the numbers is located in this repo here:

https://github.com/aaroncox/steemdata-reward-history/blob/master/utils/steem_per_vest.js

Even if I don't update them (which I plan to, gotta do taxes again next year), that should let anyone access SteemData.com's database and retrieve them without me.
